clj-commons/rewrite-clj

- src/rewrite_clj/zip/insert.clj
- test/rewrite_clj/zip/insert_test.clj
> Whitespace aware insertion

- src/rewrite_clj/parser/string.clj
- test/rewrite_clj/parser_test.clj
Fixes xsc/rewrite-clj/issues/50.
> Fix an issue where multiline regex strings were getting clobbered.

- .github/workflows/unit-test.yml
- deps.edn
- test/rewrite_clj/examples/cljx_test.cljc
- test/rewrite_clj/paredit_test.cljc
Hey there, I was experimenting with Eastwood for this project for its development. The results were satisfactory; it also found some useful things so I thought I'd contribute them over here.
> Setup and satisfy Eastwood

- src/rewrite_clj/node/coercer.cljc
- test/rewrite_clj/node/coercer_test.cljc
> [#161] Add coercer for Cons

- .clj-kondo/config.edn
- bb.edn
- deps.edn
- package-lock.json
- package.json
Of note:
- configured new linters for clj-kondo
> internal and test deps: bump

- test/rewrite_clj/node/coercer_test.cljc
Thanks to @borkdude for noticing we weren't really covering here.
Amendment to #176
> Additional test for embedded quote string coercion

- .github/workflows/code-coverage.yml
- .github/workflows/libs-test.yml
- .github/workflows/native-image-test.yml
- .github/workflows/unit-test.yml
I think this might be the sauce needed to trigger:
- test workflows only on pull requests against main branch and pushes to main branch (merges or direct pushes)
- code coverage analysis only on pushes to main branch
Closes #220
> Adjust github actions workflow triggers

- .github/workflows/libs-test.yml
- .github/workflows/native-image-test.yml
- .github/workflows/unit-test.yml
> ci: allow test workflows to be called from publish

- bb.edn
- deps.edn
- package-lock.json
- package.json
- script/test_libs.clj
also: small correction to bb task desc
> maint: bump internal deps for build and test

- src/rewrite_clj/zip.cljc
Our import-vars happens via code generation.
Ran `bb apply-import-vars gen-code` then checked in the updated generated code.
> build: apply-import-vars gen-code

- .github/workflows/native-image-test.yml
- deps.edn
- package-lock.json
- package.json
exception: leave lein at 2.10.0 for now to support refactor-nrepl lib test.
> tests & ci: bump deps to current

- bb.edn
- deps.edn
- package-lock.json
- package.json
- script/test_libs.clj
exception: leave lein at 2.10.0 for now to support refactor-nrepl lib test.
> test & ci: bump deps to current

- script/helper/graal.clj
There was old/unnecessary chuff in there.
Reviewed and modernized somewhat.
Also was not deleting existing test executable correctly, fixed.
> maint: tests: review GraalVM native-image args

- script/ci_unit_tests.clj
macos-latest is now arm-based and does not include jdk8
Closes #265
> ci: adapt to macos-latest image hardware changes

- .github/workflows/libs-test.yml
- .github/workflows/native-image-test.yml
- .github/workflows/unit-test.yml
Codecov github action + help with configuring token from clj-commons github org admins (I don't have privs) seems to have worked.
> ci codecov: re-enable other workflows

- doc/04-maintainer-guide.adoc
> docs: update maintainer guide re codecov token

- deps.edn
- package-lock.json
- package.json
Of note: now testing against clojure 1.12.0-beta1!
> test & ci: bump deps

- test/rewrite_clj/parser_test.cljc
When studying some metadata tests I converted them from `are` to `doseq`. A personal pref that I find easier to maintain and grok.
Was studying tests for #279 and #280
> test: refactor are->doseq

- .clj-kondo/config.edn
- test/rewrite_clj/custom_zipper/core_test.cljc
- test/rewrite_clj/examples/cljx_test.cljc
- test/rewrite_clj/node/coercer_test.cljc
- test/rewrite_clj/node_test.cljc
- test/rewrite_clj/parser_test.cljc
- test/rewrite_clj/zip/base_test.cljc
- test/rewrite_clj/zip/editz_test.cljc
- test/rewrite_clj/zip/findz_test.cljc
- test/rewrite_clj/zip/insert_test.cljc
- test/rewrite_clj/zip/move_test.cljc
- test/rewrite_clj/zip/removez_test.cljc
- test/rewrite_clj/zip/seqz_test.cljc
- test/rewrite_clj/zip/walk_test.cljc
- test/rewrite_clj/zip/whitespace_test.cljc
- test/rewrite_clj/zip_test.cljc
Also add a clj-kondo discouraged-var linter to enforce are-less tests.
Closes #287
> test: migrate from clojure.test/are -> doseq

- .clj-kondo/etaoin/etaoin/config.edn
- bb.edn
- deps.edn
- package-lock.json
- package.json
- script/test_libs.clj
> dev & ci: bump deps

- CHANGELOG.adoc
> changelog for #305

- README.adoc
New target describes babashka badges
See https://github.com/babashka/babashka/issues/1798
[skip ci]
> docs: readme: update babashka badge target

- deps.edn
> dev: bump flow-storm

- deps.edn
Can't resist trying out a new version of clj-kondo!
> dev: bump deps

- deps.edn
- package-lock.json
- package.json
Of note: new version of cljs is working out some kinks.
> dev & test: bump deps

- src/rewrite_clj/custom_zipper/core.cljc
I notice small mistake, i fix it.
> fix docstring mistake; left -> right
