src/rewrite_clj/node.clj, src/rewrite_clj/node/coerce.clj, src/rewrite_clj/node/whitespace.clj, src/rewrite_clj/parser/whitespace.clj, src/rewrite_clj/reader.clj, test/rewrite_clj/node/generators.clj
This is more of a RFC than a finished PR, as this badly breaks the test suite and requires a change to the programming interface.
While "," is lexical whitespace in Clojure, it doesn't make sense from the perspective of indentation or rewriting tools to treat it as such. In the case of trailing commas it works ... okay. Because "," is treated as whitespace tools like cljfmt which remove trailing "whitespace" will tend to rewrite comma paired maps. From the indenter's perspective there really isn't a good logical way around this, as preserving trailing commas requires introspecting and rewriting trailing whitespace to minimize it, rather than simply understanding that `#",+"` is significant whitespace which should not simply be discarded.
I consider the two following cases to be "correct" …
=> Create a comma node and add parser support

src/rewrite_clj/parser/core.clj, src/rewrite_clj/reader.clj, test/rewrite_clj/parser_test.clj
This changeset adds "sharp" reader support for the #?@ unquote reader
macro, added in Clojure 1.7.0. Unfortunately the parser is somewhat
complicated because there are three #? cases:
1. #? ...
2. #?@ ...
3. #?foo ...
The first case was already correctly handled. The second case requires
extending the parser to recognize \?\@, which requires consuming an
additional character from the reader before delegating to reading
subsequent form. Unfortunately to handle the third case correctly, we
need to push the \? back onto the reader, before simply reading a pair
of tokens.
Fixes xsc/rewrite-clj#46
=> Implement reader support for #?@

src/rewrite_clj/node.clj, src/rewrite_clj/node/regex.clj, src/rewrite_clj/parser/core.clj, src/rewrite_clj/parser/string.clj, test/rewrite_clj/parser_test.clj
This node type stores the pattern string, instead of using generic token nodes
that store java.util.Pattern objects.
This new node type lets `node/sexpr` return the expanded `(re-pattern "pattern-string")` form instead of a `java.util.Pattern` object.
java.util.Pattern instances cannot be compared using equals,
which would prevent comparison of sexprs generated by node/sexpr
that contain regex forms
By returning the expanded `re-pattern` form meaningful comparisons can be made
=> Use a separate node type for regex forms

README.md
Following the documentation step by step wasn't working now, since form was not defined and there was a syntax error in the line doing the parsing.
=> Define form and add a missing bracket in the README

src/rewrite_clj/node/meta.clj, test/rewrite_clj/parser_test.clj
=> Merge metadata when converting to s-expression instead of replacing it

.travis.yml, src/rewrite_clj/reader.clj
This is necessary on newer versions of c.t.r to prevent "Pushback buffer
overflow"
Fixes #60
=> Provide buffer size to tools.reader/indexing-push-back-reader

src/rewrite_clj/node.clj, src/rewrite_clj/node/seq.clj, src/rewrite_clj/parser/core.clj, test/rewrite_clj/parser_test.clj
Based on #56, adding support for keyword-namespaced maps (`#:x{:y 1}`) and alias-namespaced maps (`#::x{:y 1}`).
Still missing is support for self-namespaced maps (`#::{:y 1}`).
=> Improve partial support for namespaced maps

src/rewrite_clj/parser.cljc, test/rewrite_clj/parser_test.cljc, test/rewrite_clj/zip_test.cljc
The end position of the root node of a parsed string was inherited from the first child. This meant that the root node looked like it spanned only one child, instead of all of its children. This fix makes the root node take its end position from its last child.
After this fix, the end position of an untracked zipper (which uses the parser's data) matches the end position of a tracked zipper (which uses node extents).
This fixes #173. My one concern with this approach is that it uses `last`, meaning an additional iteration over the root node's children. Since `parse-all` already does a `doall` on the children, this isn't forcing a previously lazy sequence. But, I suppose it could still be a slight performance degradation. If you'd like I can benchmark before and after. One option would be …
=> Fix end position on root node of untracked zipper

src/rewrite_clj/reader.cljc, test/rewrite_clj/parser_test.cljc
Exceptions thrown by the reader will have `:row` and `:col` keys in their ex-data.
=> Transport position in ex-data

.github/workflows/unit-test.yml, bb.edn, doc/02-developer-guide.adoc, script/ci_unit_tests.clj, script/helper/jdk.clj, script/test_shadow_cljs.clj
Treat tests to run as data.
Have GitHub Actions source its matrix from that data.
This allows us more flexibility in adapting to changes (ex. shadow-cljs now
requires >= jdk11)
It greatly breaks down granularity of tests.
Although we might have gone a bit too far here?
We'll see and adapt as necessary.
=> ci: rework unit tests

script/test_libs.clj
Adjusted test runners for:
- clerk
- clojure-lsp
zprint has a new release, but its not for prod, so we'll skip it.
=> lib canary tests: bumps

CHANGELOG.adoc, doc/01-user-guide.adoc, src/rewrite_clj/zip.cljc, src/rewrite_clj/zip/base.cljc, src/rewrite_clj/zip/walk.cljc, template/rewrite_clj/zip.cljc, test/rewrite_clj/zip/base_test.cljc
These new zip API functions are the same as their of-string and of-file counterparts except that they do no auto navigation at all.
Closes #189
=> Add rewrite-clj.zip of-string* and of-file*

pom.xml
`rewrite-clj` is distributed under the MIT license, but this is not reflected in the `pom.xml`. Therefore tools like `clojure -T:deps list` will not recognise the license.
This PR adds a `<licenses>` tag to `pom.xml`.
=> Add MIT License to pom.xml

.github/workflows/code-coverage.yml, .github/workflows/libs-test.yml, .github/workflows/native-image-test.yml, .github/workflows/release.yml, .github/workflows/unit-test.yml, bb.edn, deps.edn, doc/02-developer-guide.adoc, package-lock.json, package.json, script/helper/env.clj
Of note: native image tests now running under GraalVM 22.3.0. There is now also an experimental JDK19 version of Graal - we'll skip this for now.
=> ci and unit test deps: bump

.github/workflows/libs-test.yml, .github/workflows/unit-test.yml
There are no Ubuntu jammy planck binaries yet.
For now we'll hack around this by using the Ubuntu focal binaries for planck on yammy.
That last official binaries built for planck on ubuntu are v2.25.0. So we are behind the current planck version of v2.27.0. But that's probably fine for now.
=> maint: hack: use focal planck on jammy

doc/01-user-guide.adoc
These seem sensible, although it also would make sense to leave them as `n/a` since symbol behavior isn't exactly analogous to that of keywords.
Cheers - V
=> doc: clarify that stand-alone symbols do not support Clojure's auto-resolve

README.adoc, script/test_libs.clj
new libs using rewrite-clj:
- kit - can add to lib tests if repo starts version tagging
- rich-comment-tests - woot!
new release of existing: antq
=> canary tests: 2 new, 1 update

CHANGELOG.adoc, src/rewrite_clj/node.cljc, src/rewrite_clj/node/coercer.cljc, src/rewrite_clj/node/string.clj, src/rewrite_clj/node/stringz.cljc, src/rewrite_clj/node/token.cljc, test/rewrite_clj/node/coercer_test.cljc
As in v0, strings are once again coerced to token nodes (instead of string nodes).
Effective fixes for coerced strings:
1. character escaping handled automatically
2. string `"a\nb\nc"` is no longer interpreted as a string appearing on multiple lines.
Bring some clarity to rewrite-clj.node/string-node's usage and
expectations via its docstring.
Alternative to PRs #216 and #217.
Fixes #214
=> Revert to v0 behaviour for string coercion

.github/workflows/native-image-test.yml, doc/02-developer-guide.adoc
We use GraalVM to test that rewrite-clj works, and continues to work, as an executable created by native-image.
=> maint: bump GraalVM to current release

src/rewrite_clj/zip/subedit.cljc
Function is analogous to thread-last, but had `->` in docstring
=> Typo fix: `subedit->>` docstring

.clj-kondo/http-kit/http-kit/config.edn, .clj-kondo/http-kit/http-kit/httpkit/with_channel.clj, .github/workflows/code-coverage.yml, .github/workflows/libs-test.yml, .github/workflows/native-image-test.yml, .github/workflows/publish.yml, .github/workflows/unit-test.yml, deps.edn, package-lock.json, package.json, script/test_libs.clj
Of note: there was a new ClojureScript release v1.11.121, but I currently see no evidence that this is an official supported release so skipping for now.
=> maint: bump internal deps for build and test

.github/workflows/native-image-test.yml, deps.edn, doc/02-developer-guide.adoc, script/helper/graal.clj
Drop testing for GraalVM JDK 17 and 20.
GraalVM JDK 21 returns version as major-only, which is a bit odd. Had to adjust some version parsing here and in sci-test.
=> test: bump GraalVM JDK to 21

CHANGELOG.adoc, deps.edn, script/test_libs.clj
This is a rewrite-clj dep and will be picked up by users of rewrite-clj.
=> bump org.clojure/tools.reader to version 1.3.7

.github/workflows/libs-test.yml, .github/workflows/native-image-test.yml, .github/workflows/shared-setup/action.yml, .github/workflows/unit-test.yml, bb.edn, deps.edn, script/test_clj.clj, script/test_libs.clj, script/test_native.clj, script/test_native_sci.clj
Clojure 1.12 alpha is mature enough to test against it.
No changes to tests, will handle new meta syntax separately.
=> tests & ci: Add Clojure 1.12 alpha

.clj-kondo/taoensso/encore/config.edn, .clj-kondo/taoensso/encore/taoensso/encore.clj, .github/workflows/native-image-test.yml, README.adoc, bb.edn, deps.edn, package-lock.json, package.json, script/test_libs.clj
Bump test and ci deps and tools to current releases.
Skipped kaocha v1.88.1376 as it seems to break clojure v1.9 compatibility. We'll wait to see if that was intentional before upgrading.
Add clj-mergetool to our lib canary tests. Closes #262.
=> test & ci: bump deps, canary test clj-mergetool

CHANGELOG.adoc, deps.edn, script/test_libs.clj
Bump our only lib dep to current latest.
I don't see anything of concern in the diff (the current release of rewrite-clj uses 1.3.6):
https://github.com/clojure/tools.reader/compare/v1.3.6...v1.4.2
Rationales for bump:
- We want to ensure rewrite-clj works with tools.reader latest
- As part of the Clojure ecosystem, we'd like to use the latest versions of libs when possible to help validate their correctness
=> maint: bump tools.reader

.clj-kondo/config.edn, deps.edn, package-lock.json, package.json
Of note:
- Can't resist trying a new release of clj-kondo! Enabled new linter: `:redudant-str-call`.
=> test & ci: bump deps

CHANGELOG.adoc, doc/01-user-guide.adoc, src/rewrite_clj/node/meta.cljc, test/rewrite_clj/parser_test.cljc
We also now throw when trying to sexpr invalid metadata.
Closes #280
=> sexpr on tag metadata now expands to long form

CHANGELOG.adoc, src/rewrite_clj/node/meta.cljc, test/rewrite_clj/parser_test.cljc
=> Add support for Clojure 1.12 vector metadata

CHANGELOG.adoc, src/rewrite_clj/interop.cljc, src/rewrite_clj/parser/token.cljc, src/rewrite_clj/reader.cljc, test/rewrite_clj/node/coercer_test.cljc, test/rewrite_clj/node_test.cljc, test/rewrite_clj/parser_test.cljc
The new `foo/3` was reader-illegal prior to 1.12.
Bring in and customize some tools.reader bits and bobs to support reading this new syntax.
Clojure's `symbol` allows us to construct technically illegal symbols, we take advantage of this to test and support this new syntax in any version of Clojure via, for example, `(symbol "foo" "3")`.
Closes #279
=> Support Clojure 1.12 array class tokens

CHANGELOG.adoc
Was not linking to contributors.
Was not always linking to issue/pr.
Use adoc attributes to make this a little less error prone and easy to maintain.
[skip ci]
=> docs: changelog: link to issue and contributors

.gitignore, script/cljdoc_preview.clj
For security reasons, docker is no longer so happy to mount volumes from `/tmp`, so move our cljdoc db dir to `~/.cljdoc-preview`.
Also minor babashka modernizations.
=> dev: cljdoc-preview tweaks [skip ci]

CHANGELOG.adoc, doc/01-user-guide.adoc
=> doc: user guide: sexpr and invalid escaped char

.gitignore, bb.edn, deps.edn, doc/02-developer-guide.adoc, script/dev_repl.clj
Convenience dev tasks to launch nREPL servers.
=> dev: add dev-jvm and dev-cljs bb tasks

bb.edn, deps.edn, package-lock.json, package.json, script/test_libs.clj
=> test & ci: bump deps, add test lib

deps.edn, package-lock.json, package.json, script/publish.clj
Of note:
- clojure 1.12 beta2!
- bb `pubcheck` task can now run checks on unpushed branch
=> test & ci: bump deps, tweak pubcheck

deps.edn, script/lint_kondo.clj
Also, take advantage of clj-kondo's new ability to copy configs and create cache at same time.
=> dev: bump da kondo

.github/workflows/native-image-test.yml, deps.edn, script/dev_repl.clj, script/test_jvm_sci.clj, script/test_native.clj, script/test_native_sci.clj
Now that clojure 1.12 has gone gold:
- reduce native image test to 1.12 only (was 1.11 and 1.12)
- whereever we were specifying 1.11 specify 1.12 instead
=> dev & ci: more clojure 1.12

README.adoc, script/test_libs.clj
See https://github.com/clojure-emacs/refactor-nrepl/issues/409
=> test: temporarily disable refactor-nrepl lib tests

CHANGELOG.adoc, src/rewrite_clj/reader.cljc, test/rewrite_clj/parser_test.cljc
=> Fix parsing of b// symbol

.github/workflows/setup-planck/action.yml
GitHub Actions has bumped ubuntu to v24.04.
Planck has not released new binaries since ubuntu 2020. https://launchpad.net/~mfikes/+archive/ubuntu/planck
So we need to hack a bit.
=> ci: planck on ubuntu noble

src/rewrite_clj/paredit.cljc
Before I embark on larger changes to the paredit API, get rid of some of the odd formatting in paredit. What was with all those newlines anyway?
=> paredit: whitespace formatting only

CHANGELOG.adoc, src/rewrite_clj/paredit.cljc, test/rewrite_clj/paredit_test.cljc
`split-at-pos` no longer throws when attempting to split at string's opening quote.
Closes #350
=> paredit: split-at-pos no longer throws @ str quote

CHANGELOG.adoc, src/rewrite_clj/paredit.cljc, src/rewrite_clj/zip/removez.cljc, test/rewrite_clj/paredit_test.cljc
In-string handling now:
- no-op if pos does not locate to word (i.e. whitespace)
- no longer has off-by-one error for word deletion
Closes #343
Also contributes to #256
=> paredit: kill-one-at-pos: word in string fix

.clj-kondo/config.edn, CHANGELOG.adoc, deps.edn, src/rewrite_clj/custom_zipper/core.cljc, src/rewrite_clj/paredit.cljc, test/rewrite_clj/paredit_test.cljc
Because of #256, slurp fns had to be rewritten. During rewriting:
- address design flaw by deprecating existing `slurp` fns and adding replacement `slurp-`*`-into` fns (closes #339)
- stop adding space char when preserving slurped newlines (closes #345)
- review ambiguous `-slurp-`*-`fully` fn behaviour (closes #341)
- when slurping, don't consider a node with `#_` uneval nodes empty (closes #338)
- don't throw on rewrite-clj parseable but invalid clojure `{:a}` (closes #336)
- slurping forward fully no longer throws when slurping into an empty seq that is last item in a seq (closes #335)
- slurping backward at empty-seq at start of seq no longer throws (closes #334)
- slurp forward now slurps when at empty-seq at end of seq (closes #333)
=> paredit: slurp fixes

src/rewrite_clj/paredit.cljc, test/rewrite_clj/paredit_test.cljc
=> paredit: kill: support ops after update

src/rewrite_clj/paredit.cljc, test/rewrite_clj/paredit_test.cljc
`barf-forward` and `barf-backward` rewritten to not use `global-find-by-node`.
Contributes to #256
=> paredit: barf fns: support ops after update

CHANGELOG.adoc, src/rewrite_clj/paredit.cljc, test/rewrite_clj/paredit_test.cljc
When `pos` is at end of string marker `"` or end of sequence marker `]`, `)` etc, kill the node.
Closes #362
Rewrite of `kill-at-pos` contributes to #256
=> paredit: kill-*at-pos end of string/seq handling

CHANGELOG.adoc, src/rewrite_clj/paredit.cljc, test/rewrite_clj/paredit_test.cljc
Fixes for splice-killing-forward, splice-killing-backward, split-at-pos.
These are the final fns that relied on reader positional metadata, add in a test to confirm paredit works on zipper without this metadata.
Closes #256
=> paredit: support ops after update

CHANGELOG.adoc, deps.edn, script/test_libs.clj, test/rewrite_clj/parser_test.cljc
Bump clojure/tools.reader to v1.5.1 to pick up the fix.
Fixes #367
=> `:end-col` metadata corrected for keywords at eof

CHANGELOG.adoc, deps.edn, script/test_libs.clj
We always bump to current to make sure we work with current.
This latest version fixes metadata for numbers at end of content (which rewrite-clj was unnaffected by).
=> Bump clojure/tools.reader to v1.5.2

script/test_libs.clj
Hmm... clojure-lsp is using a sha reference to rewrite-clj. But our test-libs handles that fine.
And... maybe I should try to finish up my paredit fixes and cut a release, eh?
=> test-libs: bump clojure-lsp

script/test_libs.clj
One failing zprint v1.3.0 test skipped.
Failure is environmental and not due to rewrite-clj. See: https://github.com/kkinnear/zprint/issues/355
Did some review/housekeeping for zprint test setup.
=> lib tests: bump zprint to v1.3.0

deps.edn, doc/01-user-guide.adoc, doc/design/namespaced-elements.adoc, src/rewrite_clj/paredit.cljc
Probably a good idea to bump minor as we are deprecating some fns in paredit. And have also made significant changes to this API.
Add a warning about paredit being under development.
=> Prep for next release

.github/workflows/libs-test.yml, README.adoc, deps.edn, script/test_libs.clj
Of note: clojure-mcp depends on rewrite-clj, add it to our lib test suite
=> test: bump deps

README.adoc, deps.edn, script/test_libs.clj
I disabled lib tests for depot because its current release tests are not passing. See https://github.com/Olical/depot/issues/57
But depot is using rewrite-clj v1 now, so updated README accordingly.
=> test & dev: bump deps
